update_usage: 
  name: "Update Electricity Usage"
  description: "Manually update the electricity usage data for a specified meter point."
  fields:
    meter_point_id:
      description: "Meter point ID for which you want to update the electricity usage."
      example: "1234567"

reset_rate_limit:
  name: "Reset Rate Limit"
  description: "Reset the rate limiting counter, in case rate limit was hit and needs to be reset manually.